name: Scrape SwingPlanIt

on:
  schedule:
    - cron: "0 0 * * *" # Run every 18 hours
  workflow_dispatch:

jobs:
  run_script:
    runs-on: windows-latest
    
    permissions: write-all
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Decrypt large secret
        run: ./decrypt_secret.sh
        shell: bash
        env:
          LARGE_SECRET_PASSPHRASE: ${{ secrets.LARGE_SECRET_PASSPHRASE }}
      
      - name: Test
        run: ls ./
        
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-renv@v2
      - name: Run script
        run: Rscript scrap_swing_planit.R
        
      - name: Commit files
        run: |
          git config --local user.name github-actions
          git config --local user.email "actions@github.com"
          git add -all
          git commit -am "Daily parsing commit on $(date)"
          git push origin main
        env:
          REPO_KEY: ${{secrets.GITHUB_TOKEN}}
          username: github-actions