name: Scrape SwingPlanIt

on:
  schedule:
    - cron: "0 0 * * *" # Run every 18 hours
  workflow_dispatch:

jobs:
  run_script:
    runs-on: windows-latest
    
    permissions: write-all
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
  
      - uses: r-lib/actions/setup-r@v2
      - name: Install dependencies
        run: |
          Rscript -e "install.packages(c('rvest', 'dplyr', 'tibble', 'stringr'))"

      - name: Run script
        run: |
          set -x
          Rscript scrap_swingplanit.R || { echo 'R script failed'; exit 1; }
        
      - name: Commit files
        run: |
          git config --local user.name github-actions
          git config --local user.email "actions@github.com"
          git add -all
          git commit -am "Daily parsing commit on $(date)"
          git push origin main
        env:
          REPO_KEY: ${{secrets.GITHUB_TOKEN}}
          username: github-actions